"""change events_id column to event_id in giveaway table

Revision ID: 15659781d271
Revises: c0c9182f82e6
Create Date: 2022-04-27 03:10:54.026087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "15659781d271"
down_revision = "c0c9182f82e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "giveaway", sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.drop_constraint("giveaway_events_id_fkey", "giveaway", type_="foreignkey")
    op.create_foreign_key(
        None, "giveaway", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("giveaway", "events_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "giveaway",
        sa.Column("events_id", postgresql.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "giveaway", type_="foreignkey")
    op.create_foreign_key(
        "giveaway_events_id_fkey",
        "giveaway",
        "events",
        ["events_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("giveaway", "event_id")
    # ### end Alembic commands ###
